### ISSUE TITLE
questions about step3_polish

### ISSUE THREAD

**Issue by Eunsik-Shin** [PlusLabNLP/Sonnet-Gen#1]
I have a 2 Qs in the main/Step3_polish/polish.ipynb.
during the process, it should load a pretrained model by
-> "model_file =  'pretrained_models/reverse_comet_1e-05_adam_32_20000.pickle' 
but the /pretrained_models/ directory is empty, and I can't figure out how(or where) to train the model by myself in the repository.

also during the "Simile" process,
checkpoint files from /checkpoint-simile/ are used, but the directory is empty too.

could you tell me how I could train the models or the directories(or links) that I can find them?

**Comment by NinaTian98369** [comment]
@asuvarna31  could you share the model checkpoints?

**Comment by asuvarna31** [comment]
Hi @Eunsik-Shin, 
Thanks for your queries. You can download the requested models here : [Step3_polish](https://drive.google.com/drive/u/1/folders/1Vq1f6lICnbO88dDaqYoxHupczPdshbEt)

Imagery Model
"model_file = 'pretrained_models/reverse_comet_1e-05_adam_32_20000.pickle'

Simile Model 
Please download the model from [this repo](https://github.com/tuhinjubcse/SimileGeneration-EMNLP2020)
